---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "empire-ip-pool"
  labels:
    org: empire
spec:
  cidrs:
  - cidr: "172.18.255.200/29"
  - cidr: "2001:db8:dead:beef::0/64"
